# DATA BASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/db_car_storage
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.properties.hibernate.jdbc.lom.nom_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# HIBERNATE DDL AUTO (CREATE, CREATE-DROP, VALIDATE, UPDATE)
spring.jpa.hibernate.ddl-auto=none

# KAFKA CONFIGS
spring.kafka.bootstrap-servers=localhost:9092